services:
  fastapi:
    build:
      context: ./fast_api
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./fast_api/app:/app/app
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./MONITORING/prometheus:/etc/prometheus
      - prom_data:/prometheus
    depends_on:
      - fastapi
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./MONITORING/grafana:/etc/grafana/provisioning/datasources
volumes:
  prom_data: