services:

  fastapi:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./API/app:/app/app
      - ./MONITORING/evidently/data:/app/data
    environment:
      - DB_PATH=/app/data/predictions.db
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./MONITORING/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    depends_on:
      - fastapi
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - ./MONITORING/grafana/config:/etc/grafana/provisioning/datasources
      - ./MONITORING/grafana/data:/var/lib/grafana

  evidently:
    image: evidently/evidently-service:latest
    container_name: evidently-ui
    ports:
      - "8001:8000"
    volumes:
      - ./MONITORING/evidently/data:/app/workspace
    restart: unless-stopped

  drift-monitor:
    build:
      context: .
      dockerfile: ./MONITORING/evidently/service/Dockerfile
    container_name: drift-monitor
    ports:
      - "8002:8002"
    restart: unless-stopped
    volumes:
      # Base de données partagée avec fastapi
      - ./MONITORING/evidently/data:/app/data
      # Datasets de référence
      - ./MONITORING/evidently/reference_data:/app/reference_data
      # Rapports générés
      - ./MONITORING/evidently/reports:/app/reports
      # Logs
      - ./MONITORING/evidently/logs:/app/logs
    depends_on:
      - fastapi
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/predictions.db

volumes:
  prometheus_data: